# Generated by Django 5.2.6 on 2025-09-27 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 9, 27, 17, 52, 51, 74810, tzinfo=datetime.timezone.utc))),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
